name: stytch_dart_auth_sdk
description: A Dart SDK for stytch B2B Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.1.0
repository: https://github.com/aortem/stytch_dart_auth_sdk
homepage: https://aortem.gitbook.io/stytch-dart-auth-admin-sdk/
issue_tracker: https://github.com/aortem/stytch_dart_auth_sdk/issues
license: BSD-3

environment:
  sdk: ^3.8.1

# Add regular dependencies here.

dependencies:
  # HTTP client for API requests
  http: ^1.1.0
  # JSON serialization/deserialization
  json_annotation: ^4.8.1
  # DateTime formatting
  intl: ^0.19.0

#------------------ BUILD AND GENERATION---------------------------------
build_runner: ^2.4.7
json_serializable: ^6.7.1
build_web_compilers: ^4.0.11

#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  # Testing framework
  test: ^1.24.8
  mockito: ^5.4.3
  build_verify: ^3.1.0
  build_runner: ^2.4.7
  # Linting
  dart_style: ^2.3.4
  # Coverage reporting
  coverage: ^1.7.1
  # Git hooks
  git_hooks: any
  lints: ^3.0.0
  flutter_lints: ^3.0.0

# Optional Local Hooks for development.
git_hooks:
  hooks:
    pre-commit: ./local_dev_tools/validate_commit.dart
    commit-msg: ./local_dev_tools/validate_commit_msg.dart
    pre-push: ./local_dev_tools/validate_branch.dart